src/Entity/Tache.php
<?php

namespace App\Entity;

use App\Repository\TacheRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TacheRepository::class)]
class Tache
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'taches')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Liste $liste = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $content = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $create_at = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getListe(): ?Liste
    {
        return $this->liste;
    }

    public function setListe(?Liste $liste): static
    {
        $this->liste = $liste;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): static
    {
        $this->content = $content;

        return $this;
    }
    

    public function getCreateAt(): ?\DateTimeImmutable
    {
        return $this->create_at;
    }

    public function setCreateAt(\DateTimeImmutable $create_at): static
    {
        $this->create_at = $create_at;

        return $this;
    }

}

src/Form/TacheType.php
<?php

namespace App\Form;

use App\Entity\Tache;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TacheType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('content')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Tache::class,
        ]);
    }
}

src/Controller/TacheController.php
<?php

namespace App\Controller;

use App\Entity\Tache;
use App\Form\TacheType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/tache')]

class TacheController extends AbstractController
{
    #[Route('/', name: 'app_tache_index', methods: ['GET'])]
    public function index(): Response
    {
        return $this->redirectToRoute('app_liste_index');
    }

    #[Route('/new', name: 'app_tache_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $user = $this->getUser();
        if ($user) {
        $tache = new Tache();
        $form = $this->createForm(TacheType::class, $tache);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $tache ->setCreateAt(new \DateTimeImmutable());
            $entityManager->persist($tache);
            $entityManager->flush();

            return $this->redirectToRoute('app_tache_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('tache/new.html.twig', [
            'tache' => $tache,
            'form' => $form,
        ]);
    }
    }

    #[Route('/{id}', name: 'app_tache_show', methods: ['GET'])]
    public function show(Tache $tache): Response
    {
        return $this->render('tache/show.html.twig', [
            'tache' => $tache,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_tache_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Tache $tache, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(TacheType::class, $tache);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_tache_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('tache/edit.html.twig', [
            'tache' => $tache,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_tache_delete', methods: ['POST'])]
    public function delete(Request $request, Tache $tache, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$tache->getId(), $request->request->get('_token'))) {
            $entityManager->remove($tache);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_tache_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/tache/_delete_form.html.twig
<form method="post" action="{{ path('app_tache_delete', {'id': tache.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ tache.id) }}">
    <button class="btn">Supprimer</button>
</form>

templates/tache/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/tache/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Tache{% endblock %}

{% block body %}
    <h1>Editer</h1>

    {{ include('tache/_form.html.twig', {'button_label': 'Modifier'}) }}

    <a href="{{ path('app_tache_index') }}">back to list</a>

    {{ include('tache/_delete_form.html.twig') }}
{% endblock %}

templates/tache/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tache index{% endblock %}

{% block body %}
    <h1>Tache index</h1>
        {% for tache in taches %}
        <div class="card" style="width: 18rem;">
  <div class="card-body">
                <p>{{ tache.name }}</p>
                <p>{{ tache.content }}</p>
                <p>{{ tache.createAt ? tache.createAt|date('Y-m-d H:i:s') : '' }}</p>

                    <a href="{{ path('app_tache_show', {'id': tache.id}) }}">show</a>
                    <a href="{{ path('app_tache_edit', {'id': tache.id}) }}">edit</a>
                    {{ include('tache/_delete_form.html.twig') }}      
  </div>
</div>
        {% endfor %}
    <a href="{{ path('app_liste_index') }}">Retourne à liste</a>
    <a href="{{ path('app_tache_new') }}">Create new</a>
{% endblock %}

templates/tache/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Tache{% endblock %}

{% block body %}
    <h1>Create new Tache</h1>

    {{ include('tache/_form.html.twig') }}

    <a href="{{ path('app_tache_index', {'id': tache.id}) }}">Retourne à tâche</a>
{% endblock %}

templates/tache/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tache{% endblock %}

{% block body %}
    <h1>Tache</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ tache.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ tache.name }}</td>
            </tr>
            <tr>
                <th>Content</th>
                <td>{{ tache.content }}</td>
            </tr>
            <tr>
                <th>Create_at</th>
                <td>{{ tache.createAt ? tache.createAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>
    <a href="{{ path('app_liste_index') }}">Retourne à liste</a>
    <a href="{{ path('app_tache_edit', {'id': tache.id}) }}">edit</a>

    {{ include('tache/_delete_form.html.twig') }}
{% endblock %}